//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FocusTimer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FocusTimer.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Program.
        /// </summary>
        public static string add_program {
            get {
                return ResourceManager.GetString("add_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Concentration.
        /// </summary>
        public static string avg_concentration {
            get {
                return ResourceManager.GetString("avg_concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Active Time.
        /// </summary>
        public static string avg_time_active {
            get {
                return ResourceManager.GetString("avg_time_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Inactive Time.
        /// </summary>
        public static string avg_time_inactive {
            get {
                return ResourceManager.GetString("avg_time_inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Timer Running.
        /// </summary>
        public static string avg_time_timer_running {
            get {
                return ResourceManager.GetString("avg_time_timer_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for window....
        /// </summary>
        public static string click_window {
            get {
                return ResourceManager.GetString("click_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string concentration {
            get {
                return ResourceManager.GetString("concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration display options.
        /// </summary>
        public static string concentration_display_options {
            get {
                return ResourceManager.GetString("concentration_display_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold focus lock for:.
        /// </summary>
        public static string hold_focus_lock_for {
            get {
                return ResourceManager.GetString("hold_focus_lock_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string hour_short {
            get {
                return ResourceManager.GetString("hour_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} days.
        /// </summary>
        public static string last_n_days {
            get {
                return ResourceManager.GetString("last_n_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string minute_short {
            get {
                return ResourceManager.GetString("minute_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute(s) left..
        /// </summary>
        public static string minutes_left {
            get {
                return ResourceManager.GetString("minutes_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string non_registered_program {
            get {
                return ResourceManager.GetString("non_registered_program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause timer after:.
        /// </summary>
        public static string pause_timer_after {
            get {
                return ResourceManager.GetString("pause_timer_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program already added..
        /// </summary>
        public static string program_already_added {
            get {
                return ResourceManager.GetString("program_already_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program information.
        /// </summary>
        public static string program_info {
            get {
                return ResourceManager.GetString("program_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take into account on calculation.
        /// </summary>
        public static string programs_to_include_in_calculation {
            get {
                return ResourceManager.GetString("programs_to_include_in_calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will take effect on the next run. Restart now?.
        /// </summary>
        public static string prompt_language_change_restart {
            get {
                return ResourceManager.GetString("prompt_language_change_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Timer.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string second_short {
            get {
                return ResourceManager.GetString("second_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second(s).
        /// </summary>
        public static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show concentration status.
        /// </summary>
        public static string show_concentration {
            get {
                return ResourceManager.GetString("show_concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start focus lock for {0} min(s).
        /// </summary>
        public static string start_focus_lock_for {
            get {
                return ResourceManager.GetString("start_focus_lock_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string starting {
            get {
                return ResourceManager.GetString("starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentrated.
        /// </summary>
        public static string time_concentrated {
            get {
                return ResourceManager.GetString("time_concentrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Running.
        /// </summary>
        public static string time_timer_running {
            get {
                return ResourceManager.GetString("time_timer_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount of Usage.
        /// </summary>
        public static string time_total_usage {
            get {
                return ResourceManager.GetString("time_total_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
